### ISSUE TITLE
    Cannot find module 'qawolf' from 'test1.test.js'

### ISSUE THREAD

**Issue by chovy** [qawolf/qawolf#283]
Cannot find module 'qawolf' from 'test1.test.js'

    > 1 | const { launch } = require("qawolf");

**Comment by jperl** [comment]
What command are you running and where (locally on CI)? Is qawolf in your node_modules?

**Comment by chovy** [comment]
I installed with -`g` flag and am running locally in my project folder on Linux.

**Comment by jperl** [comment]
Can you try and run `npx jest <name>` instead -- I will be changing `qawolf test` to call that in (#235) instead of calling [`runCli`](https://github.com/qawolf/qawolf/blob/master/packages/cli/src/runTest.ts#L32) like it does now (for historical reasons that are no longer important).

**Comment by flaurida** [comment]
Thanks for reporting this 🙌

**Comment by jperl** [comment]
Tested global install works in v0.8.0-alpha.0. Although local installation `npm i -D qawolf` is still the recommended approach.
